apiVersion: v1
kind: Service
metadata:
  name: devopsheroesapi
spec:
  type: ClusterIP
  ports:
    - name: "devopsheroesapi"
      port: 5000
  selector:
    app: devopsheroesapi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopsheroesapi
  annotations:
    dev.okteto.com/generate-host: devopsheroesapi
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: devopsheroesapi
                port:
                  number: 5000
            path: /
            pathType: ImplementationSpecific
